using System.Threading.Tasks;

namespace Apocrypha.ModernUi.Services.Map;

public interface IExportCsvToGeoJsonsService
{
    /// <summary>
    /// Converts a burg csv file generated by <a href="https://azgaar.github.io/Fantasy-Map-Generator/">Azgaar's Fantasy Map Generator</a> into a geojson file.
    /// </summary>
    /// <param name="path">The path to the csv file.</param>
    /// <returns>The path to the temp geojson file</returns>
    Task<string> ConvertFile(string path);
}