//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apocrypha.WPF.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apocrypha.WPF.Resources.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character creator for D&amp;D 3.5.
        /// </summary>
        public static string ApplicationSubTitle {
            get {
                return ResourceManager.GetString("ApplicationSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apocrypha.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear dice history.
        /// </summary>
        public static string ButtonLabelClearDiceHistory {
            get {
                return ResourceManager.GetString("ButtonLabelClearDiceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit race.
        /// </summary>
        public static string ButtonLabelEditRace {
            get {
                return ResourceManager.GetString("ButtonLabelEditRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string ButtonLabelLogin {
            get {
                return ResourceManager.GetString("ButtonLabelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New character.
        /// </summary>
        public static string ButtonLabelNewCharacter {
            get {
                return ResourceManager.GetString("ButtonLabelNewCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New race.
        /// </summary>
        public static string ButtonLabelNewRace {
            get {
                return ResourceManager.GetString("ButtonLabelNewRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string ButtonLabelRegister {
            get {
                return ResourceManager.GetString("ButtonLabelRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Character.
        /// </summary>
        public static string ButtonLabelSaveCharacter {
            get {
                return ResourceManager.GetString("ButtonLabelSaveCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed..
        /// </summary>
        public static string ErrorLoginFailed {
            get {
                return ResourceManager.GetString("ErrorLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        public static string ErrorLoginIncorrectPassword {
            get {
                return ResourceManager.GetString("ErrorLoginIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username does not exist..
        /// </summary>
        public static string ErrorLoginUsernameDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorLoginUsernameDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already in use..
        /// </summary>
        public static string ErrorRegistrationEmailAlreadyInUse {
            get {
                return ResourceManager.GetString("ErrorRegistrationEmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registartion failed..
        /// </summary>
        public static string ErrorRegistrationFailed {
            get {
                return ResourceManager.GetString("ErrorRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string ErrorRegistrationPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("ErrorRegistrationPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already in use..
        /// </summary>
        public static string ErrorRegistrationUsernameAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorRegistrationUsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view type does not have a view model..
        /// </summary>
        public static string ErrorViewTypeNotReckognized {
            get {
                return ResourceManager.GetString("ErrorViewTypeNotReckognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string InputLabelConfirmPassword {
            get {
                return ResourceManager.GetString("InputLabelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string InputLabelEmail {
            get {
                return ResourceManager.GetString("InputLabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string InputLabelPassword {
            get {
                return ResourceManager.GetString("InputLabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string InputLabelUsername {
            get {
                return ResourceManager.GetString("InputLabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allignment.
        /// </summary>
        public static string LabelInputAllignment {
            get {
                return ResourceManager.GetString("LabelInputAllignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string LabelInputCharacterDisplayName {
            get {
                return ResourceManager.GetString("LabelInputCharacterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character name.
        /// </summary>
        public static string LabelInputCharacterName {
            get {
                return ResourceManager.GetString("LabelInputCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptor.
        /// </summary>
        public static string LabelSpellDescriptor {
            get {
                return ResourceManager.GetString("LabelSpellDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell school.
        /// </summary>
        public static string LabelSpellSchool {
            get {
                return ResourceManager.GetString("LabelSpellSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub school.
        /// </summary>
        public static string LabelSpellSubSchool {
            get {
                return ResourceManager.GetString("LabelSpellSubSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string LinkLabelAlreadyHaveAnAccount {
            get {
                return ResourceManager.GetString("LinkLabelAlreadyHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string LinkLabelDontHaveAnAccount {
            get {
                return ResourceManager.GetString("LinkLabelDontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHARACTER.
        /// </summary>
        public static string MenuCategoryLabelCharacter {
            get {
                return ResourceManager.GetString("MenuCategoryLabelCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOOLS.
        /// </summary>
        public static string MenuCategoryLabelTools {
            get {
                return ResourceManager.GetString("MenuCategoryLabelTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character selection.
        /// </summary>
        public static string MenuLabelCharacterSelection {
            get {
                return ResourceManager.GetString("MenuLabelCharacterSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice roller.
        /// </summary>
        public static string MenuLabelDiceRoller {
            get {
                return ResourceManager.GetString("MenuLabelDiceRoller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuLabelHome {
            get {
                return ResourceManager.GetString("MenuLabelHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string MenuLabelLogout {
            get {
                return ResourceManager.GetString("MenuLabelLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MenuLabelMenu {
            get {
                return ResourceManager.GetString("MenuLabelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string MenuLabelProfile {
            get {
                return ResourceManager.GetString("MenuLabelProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race editor.
        /// </summary>
        public static string MenuLabelRaceEditor {
            get {
                return ResourceManager.GetString("MenuLabelRaceEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell card editor.
        /// </summary>
        public static string MenuLabelSpellCardEditor {
            get {
                return ResourceManager.GetString("MenuLabelSpellCardEditor", resourceCulture);
            }
        }
    }
}
