//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apocrypha.ModernUi.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apocrypha.ModernUi.Resources.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apocrypha.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add poison phase.
        /// </summary>
        public static string ButtonLabelAddPoisonPhase {
            get {
                return ResourceManager.GetString("ButtonLabelAddPoisonPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add phase element.
        /// </summary>
        public static string ButtonLabelAddPoisonPhaseElement {
            get {
                return ResourceManager.GetString("ButtonLabelAddPoisonPhaseElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonLabelCancel {
            get {
                return ResourceManager.GetString("ButtonLabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ButtonLabelLogin {
            get {
                return ResourceManager.GetString("ButtonLabelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string ButtonLabelLogout {
            get {
                return ResourceManager.GetString("ButtonLabelLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New poison.
        /// </summary>
        public static string ButtonLabelNewPoison {
            get {
                return ResourceManager.GetString("ButtonLabelNewPoison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        public static string ButtonLabelNotLoggedIn {
            get {
                return ResourceManager.GetString("ButtonLabelNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string ButtonLabelRegister {
            get {
                return ResourceManager.GetString("ButtonLabelRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string ButtonLabelReload {
            get {
                return ResourceManager.GetString("ButtonLabelReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ButtonLabelReset {
            get {
                return ResourceManager.GetString("ButtonLabelReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonLabelSave {
            get {
                return ResourceManager.GetString("ButtonLabelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice roller.
        /// </summary>
        public static string DiceRollerViewModelTitle {
            get {
                return ResourceManager.GetString("DiceRollerViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor - Home.
        /// </summary>
        public static string EditorHomeViewModelTitle {
            get {
                return ResourceManager.GetString("EditorHomeViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC.
        /// </summary>
        public static string HeaderLabelDifficultyClassShort {
            get {
                return ResourceManager.GetString("HeaderLabelDifficultyClassShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase elemente.
        /// </summary>
        public static string HeaderLabelPhaseElements {
            get {
                return ResourceManager.GetString("HeaderLabelPhaseElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase.
        /// </summary>
        public static string HeaderLabelPoisonPhase {
            get {
                return ResourceManager.GetString("HeaderLabelPoisonPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phases.
        /// </summary>
        public static string HeaderLabelPoisonPhases {
            get {
                return ResourceManager.GetString("HeaderLabelPoisonPhases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison Summary.
        /// </summary>
        public static string HeaderLabelPoisonSummary {
            get {
                return ResourceManager.GetString("HeaderLabelPoisonSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string HeaderLabelPreset {
            get {
                return ResourceManager.GetString("HeaderLabelPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string HeaderLabelTheme {
            get {
                return ResourceManager.GetString("HeaderLabelTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeViewModelTitle {
            get {
                return ResourceManager.GetString("HomeViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string InputHintConfirmPassword {
            get {
                return ResourceManager.GetString("InputHintConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string InputHintEmail {
            get {
                return ResourceManager.GetString("InputHintEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string InputHintPassword {
            get {
                return ResourceManager.GetString("InputHintPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string InputHintUsername {
            get {
                return ResourceManager.GetString("InputHintUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHA.
        /// </summary>
        public static string InputLabelCharismaShortCapitalized {
            get {
                return ResourceManager.GetString("InputLabelCharismaShortCapitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CON.
        /// </summary>
        public static string InputLabelConstitutionShortCapitalized {
            get {
                return ResourceManager.GetString("InputLabelConstitutionShortCapitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string InputLabelDescription {
            get {
                return ResourceManager.GetString("InputLabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEX.
        /// </summary>
        public static string InputLabelDexterityShortCapitalized {
            get {
                return ResourceManager.GetString("InputLabelDexterityShortCapitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INT.
        /// </summary>
        public static string InputLabelIntelligenceShortCapitalized {
            get {
                return ResourceManager.GetString("InputLabelIntelligenceShortCapitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase duration.
        /// </summary>
        public static string InputLabelPhaseDuration {
            get {
                return ResourceManager.GetString("InputLabelPhaseDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string InputLabelPoisonCondition {
            get {
                return ResourceManager.GetString("InputLabelPoisonCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string InputLabelPoisonDamage {
            get {
                return ResourceManager.GetString("InputLabelPoisonDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Method.
        /// </summary>
        public static string InputLabelPoisonDeliveryMethod {
            get {
                return ResourceManager.GetString("InputLabelPoisonDeliveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison name.
        /// </summary>
        public static string InputLabelPoisonName {
            get {
                return ResourceManager.GetString("InputLabelPoisonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special effect.
        /// </summary>
        public static string InputLabelPoisonSpecialEffect {
            get {
                return ResourceManager.GetString("InputLabelPoisonSpecialEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toxicity.
        /// </summary>
        public static string InputLabelPoisonToxicity {
            get {
                return ResourceManager.GetString("InputLabelPoisonToxicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race name.
        /// </summary>
        public static string InputLabelRaceName {
            get {
                return ResourceManager.GetString("InputLabelRaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size category.
        /// </summary>
        public static string InputLabelRaceSizeCategory {
            get {
                return ResourceManager.GetString("InputLabelRaceSizeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtype.
        /// </summary>
        public static string InputLabelRaceSubType {
            get {
                return ResourceManager.GetString("InputLabelRaceSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string InputLabelRaceType {
            get {
                return ResourceManager.GetString("InputLabelRaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string InputLabelRuleBook {
            get {
                return ResourceManager.GetString("InputLabelRuleBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string InputLabelRuleBookPage {
            get {
                return ResourceManager.GetString("InputLabelRuleBookPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STR.
        /// </summary>
        public static string InputLabelStrengthShortCapitalized {
            get {
                return ResourceManager.GetString("InputLabelStrengthShortCapitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIS.
        /// </summary>
        public static string InputLabelWisdomShortCapitalized {
            get {
                return ResourceManager.GetString("InputLabelWisdomShortCapitalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortitude save.
        /// </summary>
        public static string LabelFortitudeSave {
            get {
                return ResourceManager.GetString("LabelFortitudeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MenuGroupLabelTools {
            get {
                return ResourceManager.GetString("MenuGroupLabelTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dice Roller.
        /// </summary>
        public static string MenuLabelDiceRoller {
            get {
                return ResourceManager.GetString("MenuLabelDiceRoller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison Crafter.
        /// </summary>
        public static string MenuLabelPoisonCrafter {
            get {
                return ResourceManager.GetString("MenuLabelPoisonCrafter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison List.
        /// </summary>
        public static string PoisonCrafterListViewModelTitle {
            get {
                return ResourceManager.GetString("PoisonCrafterListViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison crafter.
        /// </summary>
        public static string PoisonCrafterViewModelTitle {
            get {
                return ResourceManager.GetString("PoisonCrafterViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor - Race.
        /// </summary>
        public static string RaceEditorViewModel {
            get {
                return ResourceManager.GetString("RaceEditorViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor - Races.
        /// </summary>
        public static string RaceListViewModel {
            get {
                return ResourceManager.GetString("RaceListViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string RadioButtonLabelDefault {
            get {
                return ResourceManager.GetString("RadioButtonLabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest.
        /// </summary>
        public static string RadioButtonLabelPresetForest {
            get {
                return ResourceManager.GetString("RadioButtonLabelPresetForest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavender.
        /// </summary>
        public static string RadioButtonLabelPresetLavender {
            get {
                return ResourceManager.GetString("RadioButtonLabelPresetLavender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nighttime.
        /// </summary>
        public static string RadioButtonLabelPresetNighttime {
            get {
                return ResourceManager.GetString("RadioButtonLabelPresetNighttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string RadioButtonLabelThemeDark {
            get {
                return ResourceManager.GetString("RadioButtonLabelThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string RadioButtonLabelThemeLight {
            get {
                return ResourceManager.GetString("RadioButtonLabelThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsViewModelTitle {
            get {
                return ResourceManager.GetString("SettingsViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string TabLabelDesign {
            get {
                return ResourceManager.GetString("TabLabelDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TabLabelLogin {
            get {
                return ResourceManager.GetString("TabLabelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string TabLabelRegister {
            get {
                return ResourceManager.GetString("TabLabelRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string TestViewModelTitle {
            get {
                return ResourceManager.GetString("TestViewModelTitle", resourceCulture);
            }
        }
    }
}
