name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Set path for candle and light
        run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH
        shell: bash

      - name: Restore dependencies
        # Exclude Apocrypha.Setup
        run: |
          dotnet restore ./Apocrypha.CommonObject/Apocrypha.CommonObject.csproj
          dotnet restore ./Apocrypha.CommonObject.Tests/Apocrypha.CommonObject.Tests.csproj
          dotnet restore ./Apocrypha.EntityFramework/Apocrypha.EntityFramework.csproj
          dotnet restore ./Apocrypha.ModernUi/Apocrypha.ModernUi.csproj
          dotnet restore ./Apocrypha.WPF/Apocrypha.WPF.csproj

      - name: Build Solution
        # Exclude Apocrypha.Setup
        run: |
          dotnet build ./Apocrypha.CommonObject/Apocrypha.CommonObject.csproj --configuration Release --no-restore
          dotnet build ./Apocrypha.CommonObject.Tests/Apocrypha.CommonObject.Tests.csproj --configuration Release --no-restore
          dotnet build ./Apocrypha.EntityFramework/Apocrypha.EntityFramework.csproj --configuration Release --no-restore
          dotnet build ./Apocrypha.ModernUi/Apocrypha.ModernUi.csproj --configuration Release --no-restore
          dotnet build ./Apocrypha.WPF/Apocrypha.WPF.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}